### ISSUE TITLE
Suggestion Auto Leave Duels Arena

### ISSUE THREAD

**Issue by TimDegraaf** [Dartanman/Duels#3]
When a player runs the cmd /duels join 1v1 if another player has not join the queue in x amount of times they are forcefully kicked from the duels because some players go somewhere else and then are someone joins the duel and they are teleported to the arena.

**Comment by Dartanboy** [comment]
Probably not going to add this. If you wish to be de-queued... de-queue yourself.

**Comment by Dartanboy** [comment]
Duels 3.2 will remedy this by putting players who are waiting to join in an arena-specific lobby.
