### ISSUE TITLE
Suggest: command to forfeit the duel

### ISSUE THREAD

**Issue by TimDegraaf** [Dartanman/Duels#4]
If a player decides to forfeit during the match a command would be easier to run instead of finishing the match.  Instead of ruining stats and such.

**Comment by Dartanboy** [comment]
I can do that, but a forfeit should still count as a loss, in my opinion. Otherwise, if you think you're about to lose, you could save the stats by forfeiting.

**Comment by Dartanboy** [comment]
Forfeit will be added in Duels 3.2
